name: Build GCC

on:
  push:
    branches:
      - setup_ci
      - main
  # Schedule only
  #~ schedule:
    #~ - cron: '0 0 * * 0'

jobs:
  spack_env:
    if: false
    uses: ./.github/workflows/env.yaml
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  gcc:
    name: "Spack install Firedrake inside container using GCC"
    needs: spack_env
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build firedrake-spack-gcc
        uses: docker/build-push-action@v2
        with:
          push: false
          file: .github/workflows/docker/Dockerfile.gcc
          tags: firedrakeproject/firedrake-spack-gcc:latest
